### ISSUE TITLE
Dependencies outdated

### ISSUE THREAD

**Issue by GandalfIX** [Pharb/gulp-jira-todo#1]
Would it be possible to have a release with updated dependencies, so that there are not as many security warning?

**Comment by Pharb** [comment]
Thank you for your concern. 👍 

Yes, as this project has not been updated in 5 years, the dependencies are outdated.
Feel free to open a Pull Request or fork and adapt it to your own needs.

**Comment by Pharb** [comment]
This is now resolved thanks to @ska-kialo.
@dependabot will ensure that dependencies here are kept up-to-date in the future.
